apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: weight-logger-deployer-edit-binding
  namespace: weight-logger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: weight-logger-deployer
  namespace: weight-logger
